# Assignment 1

### This Jupyter Notebook displays 5 NEW PyTorch Functions are used with Tensors

An short introduction about PyTorch and about the chosen functions. 
- torch.abs()
- torch.add()
- torch.zeros()
- torch.split()
- torch.min()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.abs()

The torch.abs() function computes the element-wise absolute value of the given input tensor.

In [2]:
# Example 1 - Working
tensor = torch.tensor([[9, 8], [-7, -6.]], dtype=torch.float64)
print("Before:", tensor)
print('')
print("After:", torch.abs(tensor))

Before: tensor([[ 9.,  8.],
        [-7., -6.]], dtype=torch.float64)

After: tensor([[9., 8.],
        [7., 6.]], dtype=torch.float64)


This example returns a tensor that contains the absolute value of each element in the "input" tensor. Notice how the -7 and -6 from the "input" tensor become positive after torch.abs() is called.

In [3]:
# Example 2 - Working
tensor = torch.tensor([[-9, -8], [-7, -6]], dtype=torch.float64)
print("Before:", tensor)
print('')
print("After:", torch.abs(tensor))

Before: tensor([[-9., -8.],
        [-7., -6.]], dtype=torch.float64)

After: tensor([[9., 8.],
        [7., 6.]], dtype=torch.float64)


This example returns a tensor that contains the absolute value of each element in the "input" tensor. Notice how all of the elements from the "input" tensor become positive after torch.abs() is called.

In [4]:
# Example 3 - Breaking (to illustrate when it breaks)
tensor = torch.tensor([[True, False], [False, True]], dtype=torch.bool)
print("Before:", tensor)
print("After:", torch.abs(tensor))

Before: tensor([[ True, False],
        [False,  True]])


RuntimeError: "abs_cpu" not implemented for 'Bool'

This function fails/gives an error because the "input" tensor contains Boolean elements, which is not a real number. However, if the "input" tensor contains integers or floats as elements, the function will not fail/give an error.

This function is useful when you need to return a tensor that contains the absolute value of each element in the "input" tensor.

## Function 2 - torch.add()

The torch.add() function adds a scalar value to each element of the input tensor and returns a new resulting tensor.

In [5]:
# Example 1 - Working
tensor_1 = torch.tensor([[-9, -8], [-7, -6]], dtype=torch.float64)

torch.add(tensor_1, 5)

tensor([[-4., -3.],
        [-2., -1.]], dtype=torch.float64)

This example returns a tensor that adds a scalar value of 5 to each element in the "input" tensor.

In [6]:
# Example 2 - Working
tensor_2 = torch.tensor([[-15, 5], [10, 25]], dtype=torch.float64)

torch.add(tensor_2, -5)

tensor([[-20.,   0.],
        [  5.,  20.]], dtype=torch.float64)

This example returns a tensor that adds a scalar value of -5 to each element in the "input" tensor, which is equivalent to subtracting 5 from each element in the "input" tensor.

In [7]:
# Example 3 - Breaking (to illustrate when it breaks)
tensor_3 = torch.tensor([[1, 0], [0, 1]], dtype=torch.float64)

torch.add(tensor_3, 'a')

TypeError: add(): argument 'other' (position 2) must be Tensor, not str

This function fails/gives an error because the scalar value passed into the add() function is a string. However, if the scalar value passed into the function was an integer or a float, the function will not fail/give an error.

This function is useful when you need to return a tensor that is the result of adding a scalar value to each element of the "input" tensor.

## Function 3 - torch.zeros()

The torch.zeros() function returns a tensor containing zeros, with the shape defined by the variable argument size.

In [8]:
# Example 1 - Working
tensor_1 = torch.zeros(2)

tensor_1

tensor([0., 0.])

This example returns a tensor that contains 2 zeros in the form of a 1 by 2 matrix.

In [9]:
# Example 2 - Working
tensor_2 = torch.zeros(3, 2)

tensor_2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

This example returns a tensor that contains 6 zeros in the form of a 3 by 2 matrix.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)

torch.zeros(-1)

RuntimeError: Trying to create tensor with negative dimension -1: [-1]

This function fails/gives an error because the value passed into the zeros() function is negative (the size cannot be negative). However, if the value passed into the function was positive, the function will not fail/give an error.

This function is useful when you need to create a tensor that only contains zeros.

## Function 4 - torch.split()

The torch.split() function splits the "input" tensor into "chunks"/separate tensors.

In [11]:
# Example 1 - Working
tensor_1 = torch.tensor([1, 3, 2, 4])
t1, t2 = torch.split(tensor_1, 2)

t1

tensor([1, 3])

This example splits a tensor containing a 1 by 4 matrix into 2 separate tensors containing a 1 by 2 matrix.

In [12]:
# Example 2 - Working
tensor_2 = torch.tensor([4, 3, 2, 1])
t1, t2, t3, t4 = torch.split(tensor_2, 1)

t1

tensor([4])

This example splits a tensor containing a 1 by 4 matrix into 4 separate tensors containing a 1 by 1 matrix.

In [13]:
# Example 3 - Breaking (to illustrate when it breaks)
tensor_3 = torch.tensor([1, 2, 3])
t1 = torch.split(tensor_3, -3)

t1

RuntimeError: split expects split_size be non-negative, but got split_size=-3

This function fails/gives an error because the split_size value passed into the split() function is negative (the split_size cannot be negative). However, if the split_size value passed into the function was positive, the function will not fail/give an error.

This function is useful when you need to assign multiple subsections of a tensor to separate tensors.

## Function 5 - torch.min()

The torch.min() function returns the minimum value of all elements in the "input" tensor.

In [14]:
# Example 1 - Working
tensor_1 = torch.tensor([4, 3, 2, 1])
min_val = torch.min(tensor_1)

min_val

tensor(1)

This example returns a value of 1 that represents the minimum value of all elements in tensor_1.

In [15]:
# Example 2 - Working
tensor_2 = torch.tensor([99])
min_val = torch.min(tensor_2)

min_val

tensor(99)

This example returns a value of 99 that represents the minimum value of all elements in tensor_2, which contains 1 element.

In [16]:
# Example 3 - Breaking (to illustrate when it breaks)
tensor_3 = torch.tensor([])
min_val = torch.min(tensor_3)

min_val

RuntimeError: operation does not have an identity.

This function fails/gives an error because the tensor passed into the min() function does not contain any elements. However, if the tensor passed into the function is not empty, the function will not fail/give an error.

This function is useful when you need to find the minimum value of all of the elements in the "input" tensor.

## Conclusion

In this notebook, we went over 5 of many different tensor functions that are in PyTorch: abs(), add(), zeros(), split(), min(). To learn about more tensor functions, you can visit https://pytorch.org/docs/stable/tensors.html.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>